### PR TITLE
Cfs tc fix

### PR DESCRIPTION
**Pull request by lorenzo-gomez-windhover**
Hello everyone,

Hope you are doing well.

My team and I have a setup where we have multiple Tc CFS links that are active at the same time (for more details on this click [here](https://groups.google.com/g/yamcs/c/qRuC8wvKdbk/m/p0kVrW0wBwAJ)) . We noticed that the checksum was getting byte swapped twice, which can cause problems because the command being sent is not what is intended. We realized this was because the byte buffer(as you can see in this PR) was being shared by all of the links and the same byte was getting swapped twice. This PR attempts to fix that by making a copy of the byte array. I hope this change does not contradict assumptions made by your APIs.

Hope this explanation and fix makes sense.
Thanks
Lorenzo

### CODE REVIEW

**Comment by xpromache** [comment]
Sorry, I don't get it: is the command being sent twice on two separate
links?

**Comment by lorenzo-gomez-windhover** [comment]
Correct, the command is being sent twice(on for each link) on two separate links(Udp and Serial). This is because there are two instances of CFS running in one vehicle.

**Comment by xpromache** [comment]
But isn't it weird to send the same command to two different targets?  What if one fails, how do you know which one did what?

Why not send two commands instead of one?

**Comment by lorenzo-gomez-windhover** [comment]
You are right; it is a weird thing to do. The way we ran into this was by accident in a way. We had the two Tc links active and we would send commands and notice the issue with the byte swapping. Now if the intend with the links in YAMCS is to always send a command via a single link, then I can see what you mean. If this is the intent(to send one command per link), it feels confusing for me as a user as this behavior is not enforced by the software. I guess what I'm trying to say that perhaps it should be obvious to the user they should not send the same command via two links as it is entirely possible. It is possible that I'm missing something here. @mbenson1 might jump in and provide some more insight as he can probably go into greater detail than me about this issue.

**Comment by mbenson1** [comment]
Just to be clear, dual command paths is not our nominal conops.  Nominally, we would select one path or another, depending on which path is available at the time.  However, YAMCS allows us to have both command paths enabled simultaneously and the commands are all designed to be idempotent.  Therefore, if our system did receive two identical commands from two different sources, it would either reject the second as a duplicate (provided the sequence number is the same on both paths, which it is not), or it would just execute the second command and result in no affect (idempotent).  When we accidentally left both paths enabled, we found that the ground system didn't always send two identical commands.  Sometimes it sent 1 good command and 1 corrupted command, or 2 corrupted commands.  We can probably live with that, but the fix is trivial and value added.  The problem is the plugins are multi threaded but not thread safe.  The fix is to just make a copy of the byte buffer rather than manipulate it directly.  With that change, we could just leave both command paths enabled and let the system use whichever one goes through.  

If the standard conops for YAMCS is to only ever have a single command path active at a time, maybe it should enforce that by deselecting all command paths when a command path is enabled.  However, I don't recommend this either.  We have other projects that have multiple command paths, but to multiple systems.  A single command path to a single system at a time.  These plugins were basically designed to filter by APID.  Each system / command path has a unique set of APIDs.  So the user can select a command from the MDB, and the plugins will ensure that it gets sent to the correct command path.

**Comment by xpromache** [comment]
When I look at this code:
https://github.com/yamcs/yamcs/blob/master/yamcs-core/src/main/java/org/yamcs/management/LinkManager.java#L514

I don't see how a command can go out on two links. 
Have you modified that? Or which version of Yamcs are you using?

**Comment by xpromache** [comment]
I pushed a change to stop after finding a link on which the command could be sent. 

So now you should not have the issue with the command sent on two links, and I think we can also discard the pull request.

**Pull request closed without merging**
