### PR TITLE
Fix warning message for failed transfers

### PR DESCRIPTION
**Pull request by tniessen**

### CODE REVIEW

**Comment by xpromache** [comment]
thanks!

**Comment by tniessen** [comment]
Thanks for the fast reply! :)

**Comment by xpromache** [comment]
> Thanks for the fast reply! :)

Do you have any interest in Yamcs or are you providing fixes for random open-source repositories on github? :)

**Comment by tniessen** [comment]
> Do you have any interest in Yamcs

I'm looking into various space-related projects for [VIOLET](https://www.nanosats.eu/sat/violet), a research project at UNB :)

**Comment by xpromache** [comment]
Very nice!
Don't hesitate to ask if you have any question about Yamcs or you need help.

**Comment by tniessen** [comment]
Thank you Nicolae! :)

**Pull request merged**
