### PR TITLE
Cfs events docs

### PR DESCRIPTION
**Pull request by lorenzo-gomez-windhover**
Hello everyone,

Figured I'd update the documentation given that we added these event options.

Thanks in advance
Lorenzo

### CODE REVIEW

**Comment by xpromache** [comment]
The options you documented do not belong to the EventRecorder page.  EventRecorder  is just a short lived service that starts recording of the event streams, (probably should disappear and be replaced with some options on the event stream config).

Your options are specific for the CfsEventDecoder which does not have a page in the manual but you can make one under the server-manual/services/instance/

**Comment by xpromache** [comment]
sorry for being picky but:
1. can you please squash all your commits into one such that it does not appear you modified files which you did not (event-recorder.rst)
2. renamed cfs-event-recorder.rst to cfs-event-decoder.rst because all is doing is to decode events, not record them.

**Comment by lorenzo-gomez-windhover** [comment]
Is the force push ok to do?

**Comment by xpromache** [comment]
> Is the force push ok to do?
Yes, force push in your own repository (i.e. where it does not disturb anybody) is the way to go according to me.

**Pull request merged**
